import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/layout/Sidebar";
import Header from "@/components/common/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full">
        <div className="flex h-screen">
          <aside className="md:w-64 w-16 bg-gray-50 h-full shadow-2xl shadow-gray-200 border-r border-gray-200 fixed left-0 top-0 z-20">
            <Sidebar/>
          </aside>
          
          <div className="flex-1 md:ml-64 ml-16">
            <Header />
            <main className="bg-white overflow-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
